#!/usr/bin/env perl
use strict;
use Cwd;

my $home = glob '~';
foreach my $file_path (glob cwd().'/*'){
    my $file = (split '/', $file_path)[-1];
    if(!($file =~ /README|install*/)){
        my $to = "$home/.$file";
        if(-e $to){
            print "! ($to) exists...";
            if(-l $to){
                unlink($to);
                print "as a symlink, removed\n";
            }else{
                rename $to => "$to~";
                print "as a normal file/directory, moved to $to~...\n"
            }
        }
        symlink($file_path, $to); 
    }
}

# Setup ~/.go if it doesn't exist, and make sure we have Projects
system "touch \$HOME/.go";
system "mkdir -p \$HOME/Projects";
system "mkdir -p \$HOME/.todo";
# git push on commit
system "echo 'git push' > .git/hooks/post-commit";
system "chmod 755 .git/hooks/post-commit";
