#!/usr/bin/env perl
use strict;
use Cwd;
use File::Find qw(find);

sub to_path {
    my ($home, $files_dir, $path) = @_;
    $path =~ s/$files_dir/$home\//;
    return $path;
}

sub main () {
    my $home = glob '~';
    my $files_dir = cwd() . '/files/';

    my @files;
    # Get all files, recursively
    find({ wanted => sub { if (-f $File::Find::name) { push @files, $File::Find::name } } }, $files_dir);

    foreach my $file (@files) {
        my $to = to_path($home, $files_dir, $file);
        if(-e $to){
            print "! ($to) exists...";
            if(-l $to){
                unlink($to);
                print "as a symlink, removed\n";
            }else{
                rename $to => "$to~";
                print "as a normal file/directory, moved to $to~...\n"
            }
        }
        symlink($file, $to); 
    }
}

main();

