#!/usr/bin/env perl
use strict;
use Cwd;
use File::Find qw(find);

my $pgp_url = "https://willwolf.me/williamwolf.asc";

sub import_gpg {
    my $reval = system "which gpg2 >> /dev/null";
    if ($reval == 0) {
        print "Importing personal gpg key...\n";
        my $reval = system "curl -sSL $pgp_url | gpg --import -";
        $reval != 0 ? print "! Failed to import pgp key!\n" : ""
    } else {
        print "! gpg2 command not found. Not importing key.\n";
    }
}

sub to_path {
    my ($home, $files_dir, $path) = @_;
    $path =~ s/$files_dir/$home\//;
    return $path;
}

sub main () {
    my $home = glob '~';
    my $files_dir = cwd() . '/files/';

    my @files;
    # Get all files, recursively
    find({ wanted => sub { if (-f $File::Find::name) { push @files, $File::Find::name } } }, $files_dir);

    foreach my $file (@files) {
        my $to = to_path($home, $files_dir, $file);
        if(-e $to){
            print "! ($to) exists...";
            if(-l $to){
                unlink($to);
                print "as a symlink, removed\n";
            }else{
                rename $to => "$to~";
                print "as a normal file/directory, moved to $to~...\n"
            }
        }
        symlink($file, $to); 
    }

    # Import your personal gpg key
    import_gpg();
}

main();

