#!/usr/bin/env perl
use strict;
use v5.10;
use Cwd;

my $home = glob '~';
foreach my $file_path (glob cwd().'/*'){
    (my $file = $file_path) =~ s/^.*\/([^\/]+$)/$1/;
    if(!($file =~ /^README|install*/)){
        my $to = "$home/.$file";
        if(-e $to){
            print "! Target ($to) exists...";
            if(-l $to){
                unlink($to);
                print "as a symlink, removed\n";
            }else{
                rename $to => "$to~";
                print "as a normal file/directory, moved to $to~...\n"
            }
        }
        symlink($file_path, $to); 
    }
}

# git push on commit
system "echo 'git push' > .git/hooks/post-commit";
system "chmod 755 .git/hooks/post-commit";
