#!/usr/bin/env perl
# Simple script to replace org name in a bunch of git repos

die "Need 2 args: orig_value replacement_value" unless @ARGV == 2;

for ( glob "./*" ){
    if( -d $_  && -d "$_/.git"){
        print "updating $_\n";
        chdir($_);

        # Open the config file
        open(my $conf, '<', '.git/config') or die $!;
        my $file = do { local $/; <$conf> } =~ s/$ARGV[0]/$ARGV[1]/ir;
        close $conf;

        # Write the config file
        open(my $conf, '>', '.git/config') or die $!;
        print $conf $file;
        close $conf;

        chdir('../');
    }
}
