#!/bin/bash

# CONFIG =======================================================================
DM_CRYPT_NAME='s3backer'
LOOPBACK='/dev/loop2'
BUCKET='wws3backer'
S3_MOUNT_POINT='/tmp/s3backer'
ENC_MOUNT_POINT='/media/s3b'

# Don't Edit Below Here ========================================================

# Mounting
sudo mkdir /tmp/s3backer

sudo s3backer $BUCKET $S3_MOUNT_POINT

sudo losetup $LOOPBACK $S3_MOUNT_POINT/file
sudo cryptsetup luksOpen $LOOPBACK $DM_CRYPT_NAME 

sudo mount -o user /dev/mapper/$DM_CRYPT_NAME $ENC_MOUNT_POINT

